# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: SSH@0
  inputs:
    sshEndpoint: 'FastDBSSH'
    runOptions: 'inline'
    inline: 'cd akupay-disbursement-service; git pull; npm install; docker-compose build && docker-compose push'
    readyTimeout: '20000'

- task: SSH@0
  inputs:
    sshEndpoint: 'FastDBSSH'
    runOptions: 'inline'
    inline: 'cd disbursement-deployment; docker-compose up -d ; docker-compose up -d akupay-sos-api ; docker-compose exec akupay-sos-api pm2 startOrRestart workers.config.js --env production'
    readyTimeout: '20000'
